version: '3'

services:
  interview-bot:
    build: .
    container_name: interview-bot
    restart: always
    environment:
      - TZ=Europe/Moscow
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16